{
  imports = [
    ./desktop
    ./dos.nix
    ./espanso.nix
    ./flatpak.nix
    ./fonts.nix
    ./gaming.nix
    ./geolocation.nix
    ./input.nix
    ./ki.nix
    ./nix.nix
    ./power.nix
    ./security.nix
    ./shell.nix
    ./ssh.nix
    ./thunderbolt.nix
    ./virtualization.nix
  ];
}
